config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :photos
  root 'photos#index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :photos
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :find_photo, only: [:show, :edit, :update, :destroy]
  
  def index
    @photos = Photo.all
  end

  def show
  end

  def edit
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.create(photo_params)
    @photo.user_id = current_user.id 
    if @photo.save!
      redirect_to root_path
    else
      render :new
    end    
  end

  def update
    if @photo.update!(photo_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @photo.destroy!
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def find_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :body, :image, :remove_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-dark bg-dark">
  <a href="/" class="navbar-brand">PhotoGallery</a>
   <% if user_signed_in? %>
                <%= link_to 'プロフィール変更', edit_user_registration_path %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            <% else %>
                <%= link_to 'サインアップ', new_user_registration_path %>
                <%= link_to 'ログイン', new_user_session_path %>
                <% end %>
</nav>
    <%= yield %>
  </body>
</html>

app/views/photos/edit.html.erb
<div class = 'container'>
<%= form_for @photo do |f| %>
title <%= f.text_field :title,class: 'form-control' %>
body <%= f.text_area :body,class: 'form-control' %>
<%= f.label :画像 %><br />
<%= f.file_field :image, class: "image" %>
<p><%= f.check_box :remove_image%>画像を削除する</p> 
 <%= f.submit  '更新',class: 'btn btn-success float-right mt-2' %>
<% end %>
</div>

app/views/photos/index.html.erb
<div class = 'container'>
    <%= link_to 'newphoto', new_photo_path, class: 'btn btn-primary'%>
    <% @photos.each do |photo| %>
        <% if (photo.user_id == current_user.id)%>
            <div>
                title:<%= photo.title %><br>
                body:<%= photo.body %><br>
                user_id:<%= photo.user_id%><br>
                <%= image_tag photo.image.url, class: '' if photo.image?%>
                <%= link_to '詳細', photo_path(photo.id), class: 'btn btn-secondary'%>
                <%= link_to '編集', edit_photo_path(photo.id), class: 'btn btn-secondary' %>
            </div>
        <%end%>
    <% end %>
</div>

app/views/photos/new.html.erb
<div class = 'container'>
<%= form_for @photo do |f| %>
title <%= f.text_field :title,class: 'form-control' %>
body <%= f.text_area :body,class: 'form-control' %>
 <%= f.label :画像 %><br />
 <%= f.file_field :image, class: "image" %>
 
 <%= f.submit  '新規作成',class: 'btn btn-success float-right mt-2' %>
<% end %>
</div>

app/views/photos/show.html.erb
<%= @photo.title %>
<%= @photo.body %>
<%= image_tag @photo.image.url if @photo.image? %>
<%= link_to  "消去", photo_path(@photo.id),method: :delete %>

<%= link_to 'トップに戻る',root_path %>